# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4eda47a8fb46eedceb5a88e1d007c5055ca0ece4400b960dd58f91936312539394a0e474958cccc48b366ca529745aecbfb3333e47b8ac6285ae91d72f8f718

test:
  secret_key_base: 61fa6ec94f09cdfdec7e8b1cf1fae64c9a9b6e3037a7eca22b1170c0642fe8fba4ed291eb4e9840fd7423b949669e4f452bdaf13d903739365fd46e0940619a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
